<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="Pneumatic_Axis" Id="{6b0fdf6b-27a8-416b-b2fa-fda7ea3fc6bb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Pneumatic_Axis
VAR
    fbPneumaticAxis : FB_PneumaticAxis;

    stPneumaticAxisStruct: INT;
    stPneumaticAxisInputs: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPneumaticAxis();



]]></ST>
    </Implementation>
    <LineIds Name="Pneumatic_Axis">
      <LineId Id="14" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>