image: python:3.7.3
options:
  max-time: 1
pipelines:
  default:
     - step:
          script:
            - git submodule update --init
            - python check_fix_white_space.py
            - ./check_no_lineids.sh
            - ./check_code_before_sq_brackets.sh
            #- python twincat_version_manager.py

